CREATE TABLE PERSON (
    ID   INTEGER,
    NAME NVARCHAR2(100),
    AGE  INTEGER
);

INSERT INTO PERSON (ID, NAME, AGE) VALUES (1, null   , null);
INSERT INTO PERSON (ID, NAME, AGE) VALUES (2, 'Bill' , 20);
INSERT INTO PERSON (ID, NAME, AGE) VALUES (3, 'Susan', 30);

